Feature contact team
WalkingMachine/walkingmachine.github.io pull request #24
Opened 2016-10-23 02:55 UTC by JeffCousineau

See commits for more informations

2016-10-25 13:55 UTC, gregoirefra requested changes
Please se comment on the file change before merging. Those comment are to help further down the line of the development on the site

2016-10-25 13:55 UTC, gregoirefra commented on en/contact/index.md
> +street: 1100 Notre-Dame Ouest, Montreal, QC, H3C 1K3
The following info is redundant on each page and could also be used else where in the site please move it to _config.yml

2016-10-25 13:55 UTC, gregoirefra commented on fr/contact/index.md
> +street: 1100 rue Notre-Dame Ouest, Montreal, QC, H3C 1K3
Please se the comment on the same page in the english folder

2016-10-25 13:55 UTC, gregoirefra commented on _layouts/contact.html
> +        <h1><b>{% if {{page.lang}} == "FR" %}Téléphone:{% else %}Phone:{% endif %} </b> {{page.phone}}</h1>
The following if on the two next line could be removed for only one. This would reduce the processing of generating the page

2016-10-27 13:33 UTC, JeffCousineau commented on en/contact/index.md
> +street: 1100 Notre-Dame Ouest, Montreal, QC, H3C 1K3
ouais en fait j'avais enlever le "rue" dans la version anglaise :P mais jpeut les mettre pareil !

2016-10-27 13:45 UTC, JeffCousineau commented on _layouts/contact.html
> +        <h1><b>{% if {{page.lang}} == "FR" %}Téléphone:{% else %}Phone:{% endif %} </b> {{page.phone}}</h1>
not sure to understand....
veux tu que je fasse : if(french)...texte francais, else... texte anglais juste une fois au lieu de le répéter 3 fois ?

2016-10-27 17:53 UTC, gregoirefra commented on _layouts/contact.html
> +        <h1><b>{% if {{page.lang}} == "FR" %}Téléphone:{% else %}Phone:{% endif %} </b> {{page.phone}}</h1>
Ouais exact juste le faire une fois au lieu de 3

2016-10-28 03:16 UTC, gregoirefra commented on en/contact/index.md
> +street: 1100 Notre-Dame Ouest, Montreal, QC, H3C 1K3
En fait moi ce que je dis c'est que rue,phone,email et room c'est pareil entre francais et anglais et qu'on pourrait l'utiliser ailleur que juste dans la page de contact, genre le footer, donc je le mettrais dans le _config.yml qui est la config global du site donc utilisable dans toutes les pages

2016-11-01 08:51 UTC, gregoirefra approved these changes

2016-11-01 08:52 UTC, merged