Update project
WalkingMachine/walkingmachine.github.io pull request #34
Opened 2016-11-08 22:10 UTC by gregoirefra

This is still a WIP but it's a start

What needs to be done is :

- [ ] Translate page in english
- [ ] Move image to CDN

2016-11-09 15:15 UTC, gregoirefra commented
Il reste a valider les textes mais le tout est pret! @JeffCousineau

2016-11-12 21:20 UTC, leonorejf commented on en/project/index.md
> +Since the beginning of is participation in the [Robocup@Home](http://www.robocupathome.org/) tournament, our team has made multiple advancement on our lovely S.A.R.A, french for Autonomous robotics a
our team has worked considerably to fully develop our lovely S.A.R.A, whose name stands for  Autonomous Robotics Assistance Systems in French. Her main goal is to be able to help people at home for daily tasks, our mission is to make her as functional as possible, in order for her to be able to navigate in a domestic environment.

2016-11-12 21:20 UTC, leonorejf commented on en/project/index.md
> +To accomplish this really big project we have divided our entire group in different [team](/en/team) with each their own project. Most of then vary every year. For this year here are the most importa
To accomplish this really big project we have divided our entire team in different [departments](/en/team), each department responsible for their own smaller projects. Most of those projects differ every year.  Here are some of the most important project for each departments :

2016-11-12 21:20 UTC, leonorejf commented on en/project/index.md
> +* Rewire the entire robot to simplify it
Rewire the entire robot in order to make it more accessible and simple, for repairs

2016-11-12 21:20 UTC, leonorejf commented on en/project/index.md
> +All of our project are hosted on [GitHub](https://github.com/WalkingMachine) and are entirely open source under the MIT Licence which can be found in all our repository. Feel free to go look at our c
All of our project are hosted on [GitHub](https://github.com/WalkingMachine), and are entirely open source under the MIT Licence, which can be found in all our repository. Feel free to look at our code and offer your help, or ask us any question about our conception process. Who knows, we might end up helping each other building the next most important robot!

2016-11-12 21:20 UTC, leonorejf commented on en/project/index.md
> +* Design a new layout for the computer in the robot
for the robot's computer

2016-11-12 21:20 UTC, leonorejf commented on fr/project/index.md
> +* Optimizer nos packages ROS pour avoir une meilleure couverture de code
Optimiser

2016-11-14 15:46 UTC, JeffCousineau requested changes
Sorry j'avais oublié ça :P

2016-11-14 15:46 UTC, JeffCousineau commented on fr/project/index.md
> +Depuis le début de sa participation à la [Robocup@Home](http://www.robocupathome.org/), notre équipe a fait de multiples avancements sur notre belle S.A.R.A (Système d’Assistance Robotique Autonome).
Depuis le début de sa participation à la [Robocup@Home](http://www.robocupathome.org/), notre équipe a fait de multiples avancements sur notre belle S.A.R.A (Système d’Assistance Robotique Autonome). Sa mission est simple, venir en aide dans les tâches quotidiennes de tous, à la maison. Notre travail, par contre, est beaucoup plus complexe, la rendre la plus fonctionnelle possible dans les différentes tâches qui peuvent lui être données.

2016-11-14 15:46 UTC, JeffCousineau commented on fr/project/index.md
> +Pour accomplir ce merveilleux projet, nous avons séparé notre équipe en différent [groupe](/fr/team) avec chacun leurs projets dédiés. Ceux-ci varient d’année en année. Cette année, les plus importan
Pour accomplir ce merveilleux projet, nous avons séparé notre équipe en différents [groupes](/fr/team) avec chacun leurs projets dédiés, ceux-ci variant d’année en année. Cette année, les plus importants sont les suivants dans chaque département :

2016-11-14 15:46 UTC, JeffCousineau commented on fr/project/index.md
> +* Concevoir un nouvel espace pour l’ordi principal
ordinateur

2016-11-14 15:46 UTC, JeffCousineau commented on fr/project/index.md
> +* Implémenter le protocole CanOpen pour la communication avec la majorité des pièces composantes S.A.R.A
composants

2016-11-14 15:46 UTC, JeffCousineau commented on fr/project/index.md
> +* Optimizer le câblage interne
Optimiser

2016-11-14 15:46 UTC, JeffCousineau commented on fr/project/index.md
> +* Optimizer le bas de la structure
Optimiser

2016-11-14 15:46 UTC, JeffCousineau commented on fr/project/index.md
> +Tous nos projets sont libres d’accès sur [GitHub](https://github.com/WalkingMachine) et sont tous sous licence MIT logiciel libre. N’hésité pas d’y faire un tour pour regarder notre progression ou d’
N'hésitez

2016-11-14 15:46 UTC, JeffCousineau commented on fr/project/index.md
> +Tous nos systèmes sont conçus pour la plateforme [ROS](http://www.ros.org), le Robot Operatinf System. Cette plateforme a été choisie il y a vraiment longtemps dans l’optique de pouvoir réutiliser no
Tout nos systèmes sont conçus pour la plateforme [ROS](http://www.ros.org), le Robot Operating System. Cette plateforme fut choisie dans l’optique d'être modulable et d'avoir la capacité de réutiliser les outils que nous développons sur d'autres robots.

2016-11-14 16:22 UTC, gregoirefra commented
@JeffCousineau et @leonorejf tout est corrigé

2016-11-14 16:22 UTC, JeffCousineau approved these changes

2016-11-14 16:31 UTC, merged