Link to partnership document, french one still missing
WalkingMachine/walkingmachine.github.io pull request #39
Opened 2016-11-17 19:23 UTC by JeffCousineau

- [ ] French document to link

2016-11-17 19:42 UTC, maximeconnolly submitted a review, later dismissed
I will accept this PR when the French version of the partnership documents is up.

2016-11-24 02:48 UTC, JeffCousineau commented
Can be review and merge

2016-11-24 03:29 UTC, gregoirefra commented on en/partner/index.md
> +See our [partnership document](https://wcdn.walkingmachine.ca/documents/Walking Machine - Partnership Document.pdf) for more informations
Des espaces dans un URL peuvent souvent causer problème selon l'encodage utilisé par le client de la page. Peux-tu changer le nom du comment par quelque chose de plus simple svp?

2016-11-24 03:29 UTC, gregoirefra requested changes

2016-11-24 03:29 UTC, gregoirefra commented on fr/partner/index.md
> +Pour des demandes de partenariat, contactez-nous au walking@ens.etsmtl.ca. Téléchargez notre [document de partenariat](https://wcdn.walkingmachine.ca/documents/Walking Machine - Document de Partenari
Même commantaire que pour la version anglaise

2016-11-24 03:41 UTC, gregoirefra approved these changes

2016-11-24 03:58 UTC, merged