Update index.md
WalkingMachine/walkingmachine.github.io pull request #47
Opened 2016-11-28 18:17 UTC by leonorejf

2016-11-29 19:09 UTC, leonorejf commented
@TheDaringDan  peux tu double check la traduction

2016-11-30 20:52 UTC, leonorejf reviewed
Daniel: Voici quelques changements a amener

2016-11-30 20:52 UTC, leonorejf commented on en/competition/index.md
> +## Robocup@Home in a few lines
Robocup-at-Home summarized

2016-11-30 20:52 UTC, leonorejf commented on en/competition/index.md
> +The RoboCup@Home is held during the Robocup, the most important robotics competition in the world. The latter also showcase the Soccer, Rescue, and Junior categories. This event, held once a year, br
RoboCup-at-Home is held during Robocup, the most important robotics competition in the world. The latter also showcases the Soccer, Rescue, and Junior branches. This event, held once a year, brings together universities and colleges from around the world.

2016-11-30 20:52 UTC, leonorejf commented on en/competition/index.md
> +RoboCup@Home aims to develop robots for personal assistance with the aim of creating the perfect assistant in everyday tasks. To find the best robots, the teams make their robot do a series of tests
- measure their skills and performance in an domestic environment.
 - human-machine interaction - human en minuscule
 - dynamic environmental navigation and mapping
 - object recognition

2016-11-30 20:52 UTC, leonorejf commented on en/competition/index.md
> +The events are presented in the form of scenarios spread out over two levels of difficulty. Thus, after passing the qualification phase, the robots are confronted with level 1 scenarios. The robots t
The five teams who have accumulated the most points during the competition go on to the final round. The winning robot is the one who has accumulated the most points throughout the different stages.

2016-11-30 20:52 UTC, leonorejf commented on en/competition/index.md
> +## Last year s scenarios
Last year's scenarios

2016-11-30 20:52 UTC, leonorejf commented on en/competition/index.md
> +* Facial recognition and facial association
Facial recognition and association

2016-12-01 02:13 UTC, gregoirefra requested changes
Les changements ont été fait dans les commentaires du thread de la pull request. Merci de les mettres dans le fichier et de commit en conséquence pour que je puisse approve les changements

2016-12-06 19:24 UTC, merged